python3 train_aeacv_stereo.py --batch_size 8 \
--logdir ./checkpoints/sceneflow/aeacv_stereo \
--train_datasets sceneflow \
--num_steps 200000 \
--train_iters 22 \
--valid_iters 32 \
--spatial_scale -0.2 0.4 \
--saturation_range 0 1.4 \
--n_downsample 2 \
--sigma 32 \
--mixed_precision